import React, {FC} from 'react';
import Head from 'next/head';

interface IHeadMeta {
    title: string
    content?: string
}

export const HeadMeta: FC<IHeadMeta> = ({
  title,
  content = 'Generated by create next app',
}) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={content}/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <link rel="icon" href="/favicon.ico"/>
    </Head>
  );
};
