import Head from "next/head";
// import Image from "next/image";
// import {Geist, Geist_Mono} from "next/font/google";
import styles from "@/styles/Home.module.css";
import {useEffect, useState} from "react";
import { motion, AnimatePresence } from 'framer-motion';

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

interface Country {
    flag_url : string,
    "name_ru" : string,
    "iso_code2" : string,
    "iso_code3" : string
}

async function fetchCountries(): Promise<Country[]> {
    const res = await fetch(
        'https://gist.githubusercontent.com/sanchezzzhak/8606e9607396fb5f8216/raw/39de29950198a7332652e1e8224f988b2e94b166/ISO3166_RU.json'
    );
    if (!res.ok) {
        throw new Error('Failed to fetch countries');
    }
    return res.json();
}

export default function Countries() {

    const [countryList, setCountryList] = useState<Country[]>([]);

    const removeCountry = (code: string) => {
        setCountryList((prev) => prev.filter((country) => country.iso_code2!== code));
    };

    useEffect(() => {
        const loadCountries = async () => {
            try {
                const countries = await fetchCountries();
                setCountryList(countries);
            } catch (error) {
                console.error('Error fetching countries:', error);
            }
        };

        loadCountries();
    }, []);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <ul>
                    <AnimatePresence>
                        {countryList.map((country) => (
                            <motion.li
                                key={country.iso_code2}
                                initial={{opacity: 0, x: 100}}
                                animate={{opacity: 1, x: 0}}
                                exit={{opacity: 0, x: 100}}
                                transition={{duration: 0.5}}
                                // className={s.listItem}
                            >
                                {/*<Image*/}
                                {/*    src={`https:${country.flag_url}`}*/}
                                {/*    alt={country.name_ru}*/}
                                {/*    width={40}*/}
                                {/*    height={30}*/}
                                {/*    // className={s.flag}*/}
                                {/*/>*/}
                                <span
                                    // className={s.countryName}
                                >{country.name_ru}</span>
                                <button
                                    onClick={() => removeCountry(country.iso_code2)}
                                    // className={s.deleteButton}
                                >
                                    Delete
                                </button>
                            </motion.li>
                        ))}
                    </AnimatePresence>
                </ul>
            </main>
        </>
    );
}
