import Head from "next/head";
// import {Geist, Geist_Mono} from "next/font/google";
import s from './Countries.module.css';
import {AnimatePresence} from 'framer-motion';
import {ICountry, useCountry} from "@/assects/hooks/useCountry";
import {CountryItem} from "@/components/countryItem/CountryItem";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });


async function fetchCountries(): Promise<ICountry[]> {
    const res = await fetch(
        'https://gist.githubusercontent.com/sanchezzzhak/8606e9607396fb5f8216/raw/39de29950198a7332652e1e8224f988b2e94b166/ISO3166_RU.json'
    );
    if (!res.ok) {
        throw new Error('Failed to fetch countries');
    }
    return res.json();
}

export default function Countries() {

    const {countryList, removeCountry} = useCountry(fetchCountries);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={s.countriesContainer}>
                <h1 className={s.countriesContainerTitle}>Country List</h1>
                <ul className={s.countriesList}>
                    <AnimatePresence>
                        {countryList.map((country) => (
                            <CountryItem key={country.iso_code2} country={country} removeCountry={removeCountry}/>
                        ))}
                    </AnimatePresence>
                </ul>
            </main>
        </>
    );
}
